language: go
env:
- GO_ENV=test

before_script:
  - buffalo db create -e test
  - mkdir -p $TRAVIS_BUILD_DIR/public/assets
  - buffalo db migrate up -e test

go:
  - 1.7.x
  - master

go_import_path: github.com/slashk/mtbcal
