language: go
env:
- GO_ENV=test
- PATH=$PATH:$GOPATH/bin

before_script:
  - go install -u github.com/gobuffalo/buffalo/buffalo
  - buffalo db create -a
  # - psql -c 'create database mtbcal_test;' -U postgres
  - mkdir -p $TRAVIS_BUILD_DIR/public/assets
  - buffalo db migrate up
  - buffalo test

go:
  - 1.7.x
  - master

go_import_path: github.com/slashk/mtbcal
