development:
  dialect: "postgres"
  database: "mtbcal_development"
  host: "127.0.0.1"
  user: "postgres"
  password: "postgres"

test:
  dialect: "postgres"
  database: "mtbcal_test"
  host: "127.0.0.1"
  user: "postgres"
  password: "postgres"

docker:
  dialect: "postgres"
  database: "mtbcal_test"
  host: "db"
  user: "postgres"
  password: "postgres"

production:
  dialect: postgres
  database: mtbcal_production
  user: postgres
  password: postgres
  host: db
  pool: 25
